spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/drones
      username: root
      password: secret
      auto-index-creation: on
  profiles:
    active: demo

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /
